name: test

on: pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: example cfn_lint_args
        uses: ./
        with:
          tool_name: cfn-lint with args
          filter_mode: nofilter
          cfn_lint_args: testdata/template.yaml
          level: info

      - name: example working_directory
        uses: ./
        with:
          tool_name: cfn-lint with args
          filter_mode: nofilter
          level: info
          working_directory: testdata
