name: update
on:
  schedule:
    - cron: "25 20 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update requirements.txt
        id: update
        run: |
          mv requirements.txt requirements.old.txt
          make requirements

          # boto3 and botocore are updated very often, so ignore them
          diff <(grep -v -E 'boto(3|core)' requirements.old.txt) \
            <(grep -v -E 'boto(3|core)' requirements.txt) && true
          echo "result=$?" >> "$GITHUB_OUTPUT"
          rm requirements.old.txt

      - name: Generate token
        id: generate_token
        uses: shogo82148/actions-github-app-token@v0

      - name: commit and create a pull request
        if: ${{ steps.update.outputs.result == '1' }}
        uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          commit-message: "auto update dependencies"
