name: update
on:
  schedule:
    - cron: "25 20 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update requirements.txt
        id: update
        run: |
          cp requirements.txt requirements.old.txt
          make requirements

          diff requirements.old.txt requirements.txt && true
          echo "result=$?" >> "$GITHUB_OUTPUT"
          rm requirements.old.txt

      - name: Generate token
        id: generate_token
        uses: shogo82148/actions-github-app-token@v1

      - name: commit and create a pull request
        if: ${{ steps.update.outputs.result == '1' }}
        uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          commit-message: "auto update dependencies"
